#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami appendedsecttbl.exe - open'
FILE=../../binaries/pe/appendedsecttbl.exe
ARGS=''
CMDS="q!"
EXPECT=''
run_test