#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami appsectableW7.exe - open'
FILE=../../binaries/pe/appsectableW7.exe
ARGS=''
CMDS="q!"
EXPECT=''
run_test