#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami dllbound-redirldXP.exe - open'
FILE=../../binaries/pe/dllbound-redirldXP.exe
ARGS=''
CMDS="q!"
EXPECT=''
run_test