#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami dllnullep-dynld.exe - open'
FILE=../../binaries/pe/dllnullep-dynld.exe
ARGS=''
CMDS="q!"
EXPECT=''
run_test