#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami dllextep-ld.exe - open'
FILE=../../binaries/pe/dllextep-ld.exe
ARGS=''
IGNORE_ERR=1
CMDS="q!"
EXPECT=''
run_test
