#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami dllemptyexp-ld.exe - open'
FILE=../../binaries/pe/dllemptyexp-ld.exe
ARGS=''
CMDS="q!"
EXPECT=''
run_test