#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami dllnoexp-dynld.exe - open'
FILE=../../binaries/pe/dllnoexp-dynld.exe
ARGS=''
CMDS="q!"
EXPECT=''
run_test