#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami hdrcode.exe - open'
IGNORE_ERR=1
FILE=../../binaries/pe/hdrcode.exe
ARGS=''
CMDS="q!"
EXPECT=''
run_test
