#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami hiddenappdata1.exe - open'
FILE=../../binaries/pe/hiddenappdata1.exe
ARGS=''
CMDS="q!"
EXPECT=''
run_test