#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami imports_apimsW7.exe - open'
FILE=../../binaries/pe/imports_apimsW7.exe
ARGS=''
CMDS="q!"
EXPECT=''
run_test