#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami dep.exe - open'
FILE=../../binaries/pe/dep.exe
ARGS=''
CMDS="q!"
EXPECT=''
run_test

NAME='PE: corkami dep.exe - dep not enabled'
FILE=../../binaries/pe/no_dep.exe
ARGS='-n'
CMDS="!rabin2 -k 'pe.nx' ${FILE}"

EXPECT='false
'

run_test
