#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami tls_obfuscation.exe - open'
FILE=../../binaries/pe/tls_obfuscation.exe
ARGS=''
CMDS="q!"
EXPECT=''
run_test