#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami dummy_secnames.elf - open'
FILE=../../binaries/elf/dummy_secnames.elf
ARGS=''
CMDS="q!"
EXPECT=''
run_test