#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami regdump.elf - open'
IGNORE_ERR=1
FILE=../../binaries/elf/regdump.elf
ARGS=''
CMDS="q!"
EXPECT=''
run_test
